version: '3'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: repick/repick-nginx
    ports:
      - 80:80
    depends_on:
      - web