name: Deploy to server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

#    - name: Build and push Docker image
#      uses: docker/build-push-action@v2
#      with:
#        context: .
#        push: true
#        tags: repick/slack-bot:latest

    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t repick/slack-bot-web .
        docker push repick/slack-bot-web
#        docker build -f dockerfile-nginx -t repick/slack-bot-nginx .
#        docker push repick/slack-bot-nginx

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/ubuntu/srv/ubuntu/
          sudo chmod 666 /var/run/docker.sock
          sudo docker rm -f $(docker ps -qa)
          sudo docker pull repick/slack-bot-web:latest
          sudo docker pull repick/slack-bot-nginx:latest
          docker-compose up -d
          docker image prune -f